### ISSUE TITLE
ERROR: file size is zero, could be wrong input file or all lines are above max sent length

### ISSUE THREAD

**Issue by Binteislam** [isi-nlp/Zoph_RNN#16]
When I try to train child model for transfer learning, I get the following error;

```
ERROR: file size is zero, could be wrong input file or all lines are above max sent length
Traceback (most recent call last):
  File "/home/username/Zoph_RNN/scripts/pretrain.py", line 193, in <module>
    main()
  File "/home/fjwu/Zoph_RNN/scripts/pretrain.py", line 190, in main
    sys.exit(check_call(cmdlist, env=dict(os.environ, **{"LD_LIBRARY_PATH":"%s:%s" % (os.environ["LD_LIBRARY_PATH"], args.cuda_lib_string)})))
  File "/usr/lib/python3.5/subprocess.py", line 581, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['ZOPH_RNN', '-C', '/home/fjwu/Zoph_RNN/en_hi_data/child_data/train_set/urdu.txt', '/home/fjwu/Zoph_RNN/en_hi_data/child_data/train_set/hin.txt', 'child.nn.last', '-B', 'child.nn', '-a', '/home/fjwu/Zoph_RNN/en_hi_data/child_data/Dev_set/urdu.txt', '/home/fjwu/Zoph_RNN/en_hi_data/child_data/Dev_set/hin.txt', '--dropout', '0.500000', '--learning-rate', '0.500000', '--adaptive-decrease-factor', '0.900000', '--parameter-range', '-0.050000', '0.050000', '--whole-clip-gradients', '5.000000', '--longest-sent', '500', '--minibatch-size', '128', '--attention-model', '1', '--number-epochs', '100', '--feed-input', '1', '--train-source-input-embedding', '1', '--train-target-input-embedding', '0', '--train-target-output-embedding', '0', '--train-source-RNN', '1', '--train-target-RNN', '1', '--train-attention-target-RNN', '1', '--logfile', 'childlog.txt', '--tmp-dir-location', '/tmp/pretrain.pyv6uyrgd6']' returned non-zero exit status 1
```
none of the files I am providing as trainsource, traintarget, devsource, devtarget are of zero size.

**Comment by Binteislam** [comment]
change in the size of minibatch resolved the issue.
